version: '3.8'

services:
  frontend:
    environment:
      # For aws-amplify
      VITE_AWS_PROJECT_REGION: ${AWS_CLOUD_REGION}
      VITE_AWS_COGNITO_REGION: ${AWS_CLOUD_REGION}
      VITE_AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      VITE_AWS_COGNITO_USER_POOL_CLIENT_ID: ${AWS_COGNITO_USER_POOL_CLIENT_ID}
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: sh -c "npm install && npm run dev"

    networks:
      - microservices-network
    depends_on:
      - web_backend


  web_backend:
    build: ./backend
#    container_name: web_backend
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    ports:
      - "8532:8532"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8532"]
    networks:
      - microservices-network
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
    depends_on:
      - payment
#      - rag_pipeline
#
  payment:
    build: ./payment

    ports:
      - "8095:8095"
    networks:
      - microservices-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8095"]
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
#
  rag_pipeline:

    build: ./RAG
    ports:
      - "8231:8231"
    networks:
      - microservices-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8231"]
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
#
networks:
  microservices-network:
    driver: bridge