version: "3.8"
services:
  frontend:
    environment:
      # For aws-amplify
      VITE_AWS_PROJECT_REGION: ${AWS_CLOUD_REGION}
      VITE_AWS_COGNITO_REGION: ${AWS_CLOUD_REGION}
      VITE_AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      VITE_AWS_COGNITO_USER_POOL_CLIENT_ID: ${AWS_COGNITO_USER_POOL_CLIENT_ID}
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: sh -c "npm install && npm run dev"
networks:
  internal-network:
    driver: bridge
    name: caden

volumes:
  db:
    driver: local