#version: '3.8'
#
#services:
#  web_backend:
#    image: your-docker-repo/web_backend:latest
#    container_name: web_backend
#    ports:
#      - "8000:8000"
#    networks:
#      - microservices-network
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
#    depends_on:
#      - payment
#      - rag_pipeline
#
#  payment:
#    image: your-docker-repo/payment:latest
#    container_name: payment
#    ports:
#      - "8001:8001"
#    networks:
#      - microservices-network
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
#
#  rag_pipeline:
#    image: your-docker-repo/rag_pipeline:latest
#    container_name: rag_pipeline
#    ports:
#      - "8002:8002"
#    networks:
#      - microservices-network
#    environment:
#      - DATABASE_URL=your_database_url
#      - OTHER_ENV_VAR=your_value
#
#  frontend:
#    image: your-docker-repo/frontend:latest
#    container_name: frontend
#    ports:
#      - "3000:3000"
#    networks:
#      - microservices-network
#    environment:
#      - API_URL=http://web_backend:8000
#
#networks:
#  microservices-network:
#    driver: bridge